modLoader="javafml"
loaderVersion="[1,)"
license="AGPL-3.0-only"
issueTrackerURL="https://codeberg.org/minegasm/minegasm/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${homepage}"
authors="Minegasm contributors"
description='''${description_long}'''

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion},)"
ordering="NONE"
side="CLIENT"
