package gg.meza.feelcraft.engine;
import gg.meza.feelcraft.device.*;
import gg.meza.feelcraft.haptics.*;
import gg.meza.feelcraft.config.HapticConfig;
import java.util.ArrayList;
import java.util.List;
public final class ButtplugRenderer {
    private final HapticConfig config;
    public ButtplugRenderer(HapticConfig config) { this.config = config; }
    public List<HapticCommand> render(HapticScene scene, List<HapticDevice> devices) { long now = System.nanoTime(); List<HapticCommand> commands = new ArrayList<>(); for (HapticLayer layer : scene.layers()) for (HapticDevice device : devices) for (HapticFeature feature : device.features()) for (HapticOutputCapability output : feature.outputs()) if (layer.route().contains(output.kind())) commands.addAll(renderLayer(layer, device, feature, output, now)); return commands; }
    private List<HapticCommand> renderLayer(HapticLayer layer, HapticDevice device, HapticFeature feature, HapticOutputCapability output, long nowNs) { float max = config.maxLevelFor(output.kind()); List<HapticCommand> commands = new ArrayList<>(); long earliest = nowNs + layer.startDelayMs() * 1_000_000L; long expires = nowNs + layer.expiresAfterMs() * 1_000_000L; if (layer.primitive() instanceof HapticPrimitive.Impulse p) { float level = HapticMath.clamp(p.level() * config.globalIntensity(), 0.0f, max); if (output.kind() == OutputKind.VIBRATE || output.kind() == OutputKind.ROTATE || output.kind() == OutputKind.OSCILLATE) commands.addAll(pulse(device, feature, output, level, p.durationMs(), layer.priority(), earliest, expires, layer.coalesceKey())); else if (output.kind() == OutputKind.HW_POSITION_WITH_DURATION) { float neutral = 0.50f; float amplitude = level * config.maxLinearAmplitude(); int out = output.scale(HapticMath.clamp(neutral + amplitude, 0.0f, 1.0f)); commands.add(new HapticCommand(device.deviceIndex(), feature.featureIndex(), output.kind(), out, output.clampDuration(Math.max(40, p.durationMs())), layer.priority(), earliest, expires, layer.coalesceKey())); commands.add(new HapticCommand(device.deviceIndex(), feature.featureIndex(), output.kind(), output.scale(neutral), output.clampDuration(Math.max(60, p.releaseMs())), layer.priority(), earliest + p.durationMs() * 1_000_000L, expires + 200_000_000L, layer.coalesceKey() + ":return")); } } else if (layer.primitive() instanceof HapticPrimitive.Texture p) { float level = HapticMath.clamp(p.level() * config.textureMultiplier() * config.globalIntensity(), 0.0f, Math.min(max, 0.45f)); if (output.kind() == OutputKind.VIBRATE) commands.addAll(pulse(device, feature, output, level, p.durationMs(), layer.priority(), earliest, expires, layer.coalesceKey())); else if (output.kind() == OutputKind.HW_POSITION_WITH_DURATION || output.kind() == OutputKind.POSITION) { float position = 0.50f + (p.grain() - 0.5f) * 0.05f + level * 0.06f; commands.add(new HapticCommand(device.deviceIndex(), feature.featureIndex(), output.kind(), output.scale(position), output.kind() == OutputKind.HW_POSITION_WITH_DURATION ? output.clampDuration(p.durationMs()) : null, layer.priority(), earliest, expires, layer.coalesceKey())); } } else if (layer.primitive() instanceof HapticPrimitive.Pattern p) { for (HapticPrimitive.Beat beat : p.beats()) { if (output.kind() != OutputKind.VIBRATE) continue; float level = HapticMath.clamp(beat.level() * config.globalIntensity(), 0.0f, Math.min(max, 0.55f)); commands.addAll(pulse(device, feature, output, level, beat.durationMs(), layer.priority(), earliest + beat.atMs() * 1_000_000L, expires + beat.atMs() * 1_000_000L, layer.coalesceKey())); } } return commands; }
    private List<HapticCommand> pulse(HapticDevice d, HapticFeature f, HapticOutputCapability o, float level, int durationMs, int priority, long earliest, long expires, String coalesceKey) {
        List<HapticCommand> out = new ArrayList<>();
        out.add(new HapticCommand(d.deviceIndex(), f.featureIndex(), o.kind(), o.scale(level), null, priority, earliest, expires, coalesceKey));
        out.add(new HapticCommand(d.deviceIndex(), f.featureIndex(), o.kind(), o.scale(0.0f), null, priority, earliest + Math.max(20, durationMs) * 1_000_000L, expires + 200_000_000L, coalesceKey + ":stop"));
        return out;
    }
}
